### ISSUE TITLE
Videos, Photos, and Links Not Syncing

### ISSUE THREAD

**Issue by jonramer** [ushahidi/Ushahidi_iPhone#57]
Am I missing something? The reports with photos and videos and links are not syncing to iPhone. Any thoughts why not?

**Comment by dalezak** [comment]
What deployment are you syncing with?

**Comment by jonramer** [comment]
The maps are http://protectthesacred.crowdmap.com and compassiongames.crowdmap.com I have updated the iPhone app as of yesterday. Is this enough info from me?

**Comment by dalezak** [comment]
Thanks, looks like the API is returning valid URLs for images.

https://protectthesacred.crowdmap.com/api?task=incidents&by=all&resp=json&comments=1&limit=120

I'll investigate the issue.

**Comment by jonramer** [comment]
Thank you so much!

**Comment by dalezak** [comment]
Found the problem!

Looks like there was change to the API on Crowdmap which now returns 'type' as an integer rather than a string.

This was causing the type check to fail, therefor wasn't parsing the media properly ignoring photos, videos, links for reports.

Thanks for pointing out the bug, I'll submit an update to the App Store with a fix to the problem.

![protect_the_sacred](https://f.cloud.github.com/assets/91811/344823/649f65f8-9e0c-11e2-9d7e-8b17c20c3916.jpg)

**Comment by dalezak** [comment]
Problem fixed in upcoming release of Ushahidi iOS 3.3

**Comment by jonramer** [comment]
Awesome! You are great!!!
